service: psycopg2-lambda-layer-rdspostgresql

provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
  profile: jb
  stage: prod

layers:
  psycopg2-py38-mimamori:
    description: "psycopg2 python postgresql client library."
    buildScript: ./build.sh
    path: layer
    compatibleRuntimes:
      - python3.8
    allowedAccounts:
      - '*'
    retain: true
